import 'dart:math'; 
import 'package:flutter/foundation.dart';
// import 'package:fl_animated_linechart/fl_animated_linechart.dart';/*  */

const daily = Duration(days: 1);
var motivationalmessages = [
  "Believe you can and you're halfway there.",
  "The only way to do great work is to love what you do.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Don't watch the clock; do what it does. Keep going.",
  "It does not matter how slowly you go as long as you do not stop.",
  "The will to win, the desire to succeed, the urge to reach your full potential... these are the keys that will unlock the door to personal excellence.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Your limitation—it's only your imagination.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn’t just find you. You have to go out and get it.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Dream bigger. Do bigger.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "Little things make big days.",
  "It’s going to be hard, but hard does not mean impossible.",
  "Don’t wait for opportunity. Create it.",
  "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
  "The key to success is to focus on goals, not obstacles.",
  "Dream it. Believe it. Build it.",
  "Remember why you started.",
  "The only way to do great work is to love what you do.",
  "The future depends on what you do today.",
  "Success is the sum of small efforts repeated day in and day out.",
  "Don’t stop until you’re proud.",
  "Do what you love, and the money will follow.",
  "Believe you can and you're halfway there.",
  "Don’t watch the clock; do what it does. Keep going.",
  "You are never too old to set another goal or to dream a new dream.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "Success is not just about making money. It's about making a difference.",
  "You don’t have to be great to start, but you have to start to be great.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Success is not the key to happiness. Happiness is the key to success.",
  "Your limitation—it’s only your imagination.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "It’s never too late for a new beginning in your life.",
  "You are capable of more than you know.",
  "Difficult roads often lead to beautiful destinations.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "It’s not about how bad you want it. It’s about how hard you’re willing to work for it.",
  "Success is not in what you have, but who you are.",
  "Don’t let yesterday take up too much of today.",
  "The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.",
  "The secret of getting ahead is getting started.",
  "You are never too old to set another goal or to dream a new dream.",
  "Success is not the key to happiness. Happiness is the key to success.",
  "Believe you can and you're halfway there.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "It’s never too late for a new beginning in your life.",
  "You are capable of more than you know.",
  "Difficult roads often lead to beautiful destinations.",
  "The only way to achieve the impossible is to believe it is possible.",
  "It’s not about how bad you want it. It’s about how hard you’re willing to work for it.",
  "Success is not in what you have, but who you are.",
  "Don’t let yesterday take up too much of today.",
  "The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.",
  "The secret of getting ahead is getting started."
];
var tips = ['List 3 things that you were grateful for today, no matter how small', 
            'Let go of your online presence for a few hours today and do anything you find fun face-to-face',
            'Go outside for 20 minutes and bask in the sunlight, get some Vitamin D to elevate your mood',
            'Try to stenghten your relationships with your family and/or friends today, they are your main pillars of support'];
Future<void> motivationalnotifs() async {
  await Future.delayed(daily);
  debugPrint(motivationalmessages[Random().nextInt(motivationalmessages.length)]);
} 

