name: sunshine
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ionicons: ^0.2.2
  google_fonts: ^6.1.0
  dio: ^4.0.0
  shimmer: ^2.0.0
  flutter_native_splash: ^1.2.1
  shared_preferences: ^2.0.6
  animations: ^2.0.8
  flutter_svg: ^0.22.0
  flutter_bloc: ^8.1.3
  meta: ^1.7.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

flutter_native_splash:
    color: "#001427"
    image: assets/images/splash.png
    android: true
    ios: true
    web: false

  