name: sunshine
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  bloc: ^8.1.3
  equatable: ^2.0.5
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_ui_auth: ^1.10.0
  firebase_ui_oauth_google: ^1.2.14
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: 6.1.0
  google_sign_in: ^6.1.6
  meta: ^1.9.1
  shared_preferences: ^2.2.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  ionicons: ^0.2.2
  dio: ^5.4.1
  shimmer: ^3.0.0
  flutter_native_splash: ^2.3.7
  solar_icons: ^0.0.5  
  animations: ^2.0.8
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.3
  

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true
 

  assets:
    - assets/images/
    - assets/icons/

flutter_native_splash:
    color: "#FDFAEF"
    color_dark: "#09192A"
    image: assets/images/splash.png
    android: true
    ios: true
    web: false

  